//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MdMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MdMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MdMessage", typeof(MdMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درمان انجام شد.
        /// </summary>
        public static string ChechedRegTheratment {
            get {
                return ResourceManager.GetString("ChechedRegTheratment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اختصاصی تکراری است.
        /// </summary>
        public static string CheckDuplicateText {
            get {
                return ResourceManager.GetString("CheckDuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این بیمه گر قبلا ثبت شده است.
        /// </summary>
        public static string CheckInSurance {
            get {
                return ResourceManager.GetString("CheckInSurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمه گر مربوط به این پزشک قبلا ثبت شده است.
        /// </summary>
        public static string CheckInSuranceDoctor {
            get {
                return ResourceManager.GetString("CheckInSuranceDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن به حذف بیمار هستید؟.
        /// </summary>
        public static string CUsDelete {
            get {
                return ResourceManager.GetString("CUsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پزشک را انتخاب کنید.
        /// </summary>
        public static string DoctorMessage {
            get {
                return ResourceManager.GetString("DoctorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا در تکمیل اطلاعات دقت نمایید.
        /// </summary>
        public static string ErrorMessageInfo {
            get {
                return ResourceManager.GetString("ErrorMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی باید 10 رقمی باشد.
        /// </summary>
        public static string ErrorNational {
            get {
                return ResourceManager.GetString("ErrorNational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمه گر را انتخاب کنید.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مورد جدید.
        /// </summary>
        public static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکتر وارد نشده است .
        /// </summary>
        public static string NoDoctorIsDefiend {
            get {
                return ResourceManager.GetString("NoDoctorIsDefiend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به انجام این عملیات نیستید..
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع و پایان معتبر  نمی باشد..
        /// </summary>
        public static string StartTimeAndEndTimeValidate {
            get {
                return ResourceManager.GetString("StartTimeAndEndTimeValidate", resourceCulture);
            }
        }
    }
}
